/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_window1 (void)
{
  GtkWidget *window1;
  GtkWidget *fixed1;
  GtkWidget *notebook1;
  GtkWidget *fixed2;
  GtkWidget *label2;
  GtkWidget *label3;
  GtkWidget *label4;
  GtkWidget *label5;
  GtkWidget *label6;
  GtkWidget *label7;
  GtkWidget *label9;
  GtkWidget *entry_fnameo;
  GtkWidget *entry_nameo;
  GtkWidget *entry_phoneo;
  GtkWidget *label10;
  GtkWidget *label11;
  GtkWidget *label12;
  GtkObject *spinbutton_dayo_adj;
  GtkWidget *spinbutton_dayo;
  GtkObject *spinbutton_montho_adj;
  GtkWidget *spinbutton_montho;
  GtkObject *spinbutton_yearo_adj;
  GtkWidget *spinbutton_yearo;
  GtkWidget *label1;
  GtkWidget *label8;
  GtkWidget *entry_cino;
  GtkWidget *labelerroro1;
  GtkWidget *label32;
  GtkWidget *combobox_blocko;
  GtkWidget *combobox_levelo;
  GtkWidget *r_male;
  GSList *r_male_group = NULL;
  GtkWidget *r_fmale;
  GtkWidget *addo;
  GtkWidget *label13;
  GtkWidget *fixed3;
  GtkWidget *entrycinre;
  GtkWidget *entryblockre;
  GtkWidget *treeview1;
  GtkWidget *label16;
  GtkWidget *labelerroro2;
  GtkWidget *modifyo;
  GtkWidget *checkbutton2;
  GtkWidget *searcho;
  GtkWidget *refresho1;
  GtkWidget *checkbutton1;
  GtkWidget *label14;
  GtkWidget *fixed4;
  GtkWidget *treeview2;
  GtkWidget *labelerroro3;
  GtkWidget *label33;
  GtkWidget *entrycinree;
  GtkWidget *entryblockree;
  GtkWidget *deleteo;
  GtkWidget *checkbutton3o;
  GtkWidget *searcho4;
  GtkWidget *checkbutton4o;
  GtkWidget *refresho4;
  GtkWidget *searcho2;
  GtkWidget *fixed5;
  GtkWidget *treeview3;
  GtkWidget *label19;
  GtkWidget *refresho3;
  GtkWidget *label18;

  window1 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window1), _("hostle"));

  fixed1 = gtk_fixed_new ();
  gtk_widget_show (fixed1);
  gtk_container_add (GTK_CONTAINER (window1), fixed1);

  notebook1 = gtk_notebook_new ();
  gtk_widget_show (notebook1);
  gtk_fixed_put (GTK_FIXED (fixed1), notebook1, 0, 0);
  gtk_widget_set_size_request (notebook1, 720, 512);

  fixed2 = gtk_fixed_new ();
  gtk_widget_show (fixed2);
  gtk_container_add (GTK_CONTAINER (notebook1), fixed2);

  label2 = gtk_label_new (_("CIN"));
  gtk_widget_show (label2);
  gtk_fixed_put (GTK_FIXED (fixed2), label2, 0, 48);
  gtk_widget_set_size_request (label2, 96, 32);

  label3 = gtk_label_new (_("First Name"));
  gtk_widget_show (label3);
  gtk_fixed_put (GTK_FIXED (fixed2), label3, 0, 96);
  gtk_widget_set_size_request (label3, 96, 32);

  label4 = gtk_label_new (_("Name"));
  gtk_widget_show (label4);
  gtk_fixed_put (GTK_FIXED (fixed2), label4, 0, 152);
  gtk_widget_set_size_request (label4, 96, 32);

  label5 = gtk_label_new (_("Block"));
  gtk_widget_show (label5);
  gtk_fixed_put (GTK_FIXED (fixed2), label5, 0, 208);
  gtk_widget_set_size_request (label5, 96, 32);

  label6 = gtk_label_new (_("Level"));
  gtk_widget_show (label6);
  gtk_fixed_put (GTK_FIXED (fixed2), label6, 0, 264);
  gtk_widget_set_size_request (label6, 96, 32);

  label7 = gtk_label_new (_("Phone Number"));
  gtk_widget_show (label7);
  gtk_fixed_put (GTK_FIXED (fixed2), label7, 8, 320);
  gtk_widget_set_size_request (label7, 112, 32);

  label9 = gtk_label_new (_("Date of birth"));
  gtk_widget_show (label9);
  gtk_fixed_put (GTK_FIXED (fixed2), label9, 440, 152);
  gtk_widget_set_size_request (label9, 112, 32);

  entry_fnameo = gtk_entry_new ();
  gtk_widget_show (entry_fnameo);
  gtk_fixed_put (GTK_FIXED (fixed2), entry_fnameo, 144, 96);
  gtk_widget_set_size_request (entry_fnameo, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_fnameo), 8226);

  entry_nameo = gtk_entry_new ();
  gtk_widget_show (entry_nameo);
  gtk_fixed_put (GTK_FIXED (fixed2), entry_nameo, 144, 152);
  gtk_widget_set_size_request (entry_nameo, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_nameo), 8226);

  entry_phoneo = gtk_entry_new ();
  gtk_widget_show (entry_phoneo);
  gtk_fixed_put (GTK_FIXED (fixed2), entry_phoneo, 136, 320);
  gtk_widget_set_size_request (entry_phoneo, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_phoneo), 8226);

  label10 = gtk_label_new (_("Month"));
  gtk_widget_show (label10);
  gtk_fixed_put (GTK_FIXED (fixed2), label10, 496, 280);
  gtk_widget_set_size_request (label10, 49, 17);

  label11 = gtk_label_new (_("Year"));
  gtk_widget_show (label11);
  gtk_fixed_put (GTK_FIXED (fixed2), label11, 576, 280);
  gtk_widget_set_size_request (label11, 49, 17);

  label12 = gtk_label_new (_("Day"));
  gtk_widget_show (label12);
  gtk_fixed_put (GTK_FIXED (fixed2), label12, 424, 280);
  gtk_widget_set_size_request (label12, 49, 17);

  spinbutton_dayo_adj = gtk_adjustment_new (1, 1, 31, 1, 10, 10);
  spinbutton_dayo = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton_dayo_adj), 1, 0);
  gtk_widget_show (spinbutton_dayo);
  gtk_fixed_put (GTK_FIXED (fixed2), spinbutton_dayo, 424, 312);
  gtk_widget_set_size_request (spinbutton_dayo, 60, 27);

  spinbutton_montho_adj = gtk_adjustment_new (1, 1, 12, 1, 10, 10);
  spinbutton_montho = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton_montho_adj), 1, 0);
  gtk_widget_show (spinbutton_montho);
  gtk_fixed_put (GTK_FIXED (fixed2), spinbutton_montho, 496, 312);
  gtk_widget_set_size_request (spinbutton_montho, 60, 27);

  spinbutton_yearo_adj = gtk_adjustment_new (1, 1980, 2050, 1, 10, 10);
  spinbutton_yearo = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton_yearo_adj), 1, 0);
  gtk_widget_show (spinbutton_yearo);
  gtk_fixed_put (GTK_FIXED (fixed2), spinbutton_yearo, 568, 312);
  gtk_widget_set_size_request (spinbutton_yearo, 60, 27);

  label1 = gtk_label_new (_("ADD STUDENT"));
  gtk_widget_show (label1);
  gtk_fixed_put (GTK_FIXED (fixed2), label1, 264, 0);
  gtk_widget_set_size_request (label1, 136, 40);

  label8 = gtk_label_new (_("Gender"));
  gtk_widget_show (label8);
  gtk_fixed_put (GTK_FIXED (fixed2), label8, 440, 40);
  gtk_widget_set_size_request (label8, 112, 32);

  entry_cino = gtk_entry_new ();
  gtk_widget_show (entry_cino);
  gtk_fixed_put (GTK_FIXED (fixed2), entry_cino, 144, 48);
  gtk_widget_set_size_request (entry_cino, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_cino), 8226);

  labelerroro1 = gtk_label_new ("");
  gtk_widget_show (labelerroro1);
  gtk_fixed_put (GTK_FIXED (fixed2), labelerroro1, 280, 432);
  gtk_widget_set_size_request (labelerroro1, 120, 40);

  label32 = gtk_label_new (_("label32"));
  gtk_widget_show (label32);
  gtk_fixed_put (GTK_FIXED (fixed2), label32, 0, 0);
  gtk_widget_set_size_request (label32, 0, 0);

  combobox_blocko = gtk_combo_box_new_text ();
  gtk_widget_show (combobox_blocko);
  gtk_fixed_put (GTK_FIXED (fixed2), combobox_blocko, 144, 216);
  gtk_widget_set_size_request (combobox_blocko, 200, 29);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_blocko), _("1"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_blocko), _("2"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_blocko), _("3"));

  combobox_levelo = gtk_combo_box_new_text ();
  gtk_widget_show (combobox_levelo);
  gtk_fixed_put (GTK_FIXED (fixed2), combobox_levelo, 144, 256);
  gtk_widget_set_size_request (combobox_levelo, 192, 32);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_levelo), _("1"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_levelo), _("2"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_levelo), _("3"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_levelo), _("4"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_levelo), _("5"));

  r_male = gtk_radio_button_new_with_mnemonic (NULL, _("Male"));
  gtk_widget_show (r_male);
  gtk_fixed_put (GTK_FIXED (fixed2), r_male, 392, 80);
  gtk_widget_set_size_request (r_male, 88, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (r_male), r_male_group);
  r_male_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (r_male));

  r_fmale = gtk_radio_button_new_with_mnemonic (NULL, _("Female"));
  gtk_widget_show (r_fmale);
  gtk_fixed_put (GTK_FIXED (fixed2), r_fmale, 544, 80);
  gtk_widget_set_size_request (r_fmale, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (r_fmale), r_male_group);
  r_male_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (r_fmale));

  addo = gtk_button_new_with_mnemonic (_("ADD"));
  gtk_widget_show (addo);
  gtk_fixed_put (GTK_FIXED (fixed2), addo, 296, 392);
  gtk_widget_set_size_request (addo, 66, 29);

  label13 = gtk_label_new (_("ADD"));
  gtk_widget_show (label13);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 0), label13);

  fixed3 = gtk_fixed_new ();
  gtk_widget_show (fixed3);
  gtk_container_add (GTK_CONTAINER (notebook1), fixed3);

  entrycinre = gtk_entry_new ();
  gtk_widget_show (entrycinre);
  gtk_fixed_put (GTK_FIXED (fixed3), entrycinre, 136, 64);
  gtk_widget_set_size_request (entrycinre, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entrycinre), 8226);

  entryblockre = gtk_entry_new ();
  gtk_widget_show (entryblockre);
  gtk_fixed_put (GTK_FIXED (fixed3), entryblockre, 520, 64);
  gtk_widget_set_size_request (entryblockre, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryblockre), 8226);

  treeview1 = gtk_tree_view_new ();
  gtk_widget_show (treeview1);
  gtk_fixed_put (GTK_FIXED (fixed3), treeview1, 120, 144);
  gtk_widget_set_size_request (treeview1, 504, 280);

  label16 = gtk_label_new (_("Search By"));
  gtk_widget_show (label16);
  gtk_fixed_put (GTK_FIXED (fixed3), label16, 320, 8);
  gtk_widget_set_size_request (label16, 96, 32);

  labelerroro2 = gtk_label_new ("");
  gtk_widget_show (labelerroro2);
  gtk_fixed_put (GTK_FIXED (fixed3), labelerroro2, 424, 432);
  gtk_widget_set_size_request (labelerroro2, 176, 32);

  modifyo = gtk_button_new_with_mnemonic (_("Modify"));
  gtk_widget_show (modifyo);
  gtk_fixed_put (GTK_FIXED (fixed3), modifyo, 344, 424);
  gtk_widget_set_size_request (modifyo, 66, 29);

  checkbutton2 = gtk_check_button_new_with_mnemonic (_("Block"));
  gtk_widget_show (checkbutton2);
  gtk_fixed_put (GTK_FIXED (fixed3), checkbutton2, 440, 64);
  gtk_widget_set_size_request (checkbutton2, 72, 24);

  searcho = gtk_button_new_with_mnemonic (_("Search"));
  gtk_widget_show (searcho);
  gtk_fixed_put (GTK_FIXED (fixed3), searcho, 336, 104);
  gtk_widget_set_size_request (searcho, 72, 32);

  refresho1 = gtk_button_new_with_mnemonic (_("Refresh"));
  gtk_widget_show (refresho1);
  gtk_fixed_put (GTK_FIXED (fixed3), refresho1, 640, 280);
  gtk_widget_set_size_request (refresho1, 66, 29);

  checkbutton1 = gtk_check_button_new_with_mnemonic (_("CIN"));
  gtk_widget_show (checkbutton1);
  gtk_fixed_put (GTK_FIXED (fixed3), checkbutton1, 56, 64);
  gtk_widget_set_size_request (checkbutton1, 64, 24);

  label14 = gtk_label_new (_("Manage Student"));
  gtk_widget_show (label14);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 1), label14);

  fixed4 = gtk_fixed_new ();
  gtk_widget_show (fixed4);
  gtk_container_add (GTK_CONTAINER (notebook1), fixed4);

  treeview2 = gtk_tree_view_new ();
  gtk_widget_show (treeview2);
  gtk_fixed_put (GTK_FIXED (fixed4), treeview2, 64, 152);
  gtk_widget_set_size_request (treeview2, 512, 248);

  labelerroro3 = gtk_label_new ("");
  gtk_widget_show (labelerroro3);
  gtk_fixed_put (GTK_FIXED (fixed4), labelerroro3, 432, 432);
  gtk_widget_set_size_request (labelerroro3, 176, 32);

  label33 = gtk_label_new (_("Select a Student to delete"));
  gtk_widget_show (label33);
  gtk_fixed_put (GTK_FIXED (fixed4), label33, 224, 24);
  gtk_widget_set_size_request (label33, 224, 40);

  entrycinree = gtk_entry_new ();
  gtk_widget_show (entrycinree);
  gtk_fixed_put (GTK_FIXED (fixed4), entrycinree, 136, 64);
  gtk_widget_set_size_request (entrycinree, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entrycinree), 8226);

  entryblockree = gtk_entry_new ();
  gtk_widget_show (entryblockree);
  gtk_fixed_put (GTK_FIXED (fixed4), entryblockree, 520, 64);
  gtk_widget_set_size_request (entryblockree, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryblockree), 8226);

  deleteo = gtk_button_new_with_mnemonic (_("Delete"));
  gtk_widget_show (deleteo);
  gtk_fixed_put (GTK_FIXED (fixed4), deleteo, 344, 424);
  gtk_widget_set_size_request (deleteo, 66, 29);

  checkbutton3o = gtk_check_button_new_with_mnemonic (_("CIN"));
  gtk_widget_show (checkbutton3o);
  gtk_fixed_put (GTK_FIXED (fixed4), checkbutton3o, 56, 64);
  gtk_widget_set_size_request (checkbutton3o, 64, 24);

  searcho4 = gtk_button_new_with_mnemonic (_("Search"));
  gtk_widget_show (searcho4);
  gtk_fixed_put (GTK_FIXED (fixed4), searcho4, 336, 104);
  gtk_widget_set_size_request (searcho4, 72, 32);

  checkbutton4o = gtk_check_button_new_with_mnemonic (_("Block"));
  gtk_widget_show (checkbutton4o);
  gtk_fixed_put (GTK_FIXED (fixed4), checkbutton4o, 440, 64);
  gtk_widget_set_size_request (checkbutton4o, 72, 24);

  refresho4 = gtk_button_new_with_mnemonic (_("Refresh"));
  gtk_widget_show (refresho4);
  gtk_fixed_put (GTK_FIXED (fixed4), refresho4, 640, 280);
  gtk_widget_set_size_request (refresho4, 66, 29);

  searcho2 = gtk_label_new (_("Delete Student"));
  gtk_widget_show (searcho2);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 2), searcho2);

  fixed5 = gtk_fixed_new ();
  gtk_widget_show (fixed5);
  gtk_container_add (GTK_CONTAINER (notebook1), fixed5);

  treeview3 = gtk_tree_view_new ();
  gtk_widget_show (treeview3);
  gtk_fixed_put (GTK_FIXED (fixed5), treeview3, 112, 72);
  gtk_widget_set_size_request (treeview3, 576, 344);

  label19 = gtk_label_new (_("Number of Students per Level"));
  gtk_widget_show (label19);
  gtk_fixed_put (GTK_FIXED (fixed5), label19, 240, 8);
  gtk_widget_set_size_request (label19, 224, 32);

  refresho3 = gtk_button_new_with_mnemonic (_("Refresh"));
  gtk_widget_show (refresho3);
  gtk_fixed_put (GTK_FIXED (fixed5), refresho3, 16, 200);
  gtk_widget_set_size_request (refresho3, 66, 29);

  label18 = gtk_label_new (_("Student per Level"));
  gtk_widget_show (label18);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 3), label18);

  g_signal_connect ((gpointer) entry_cino, "grab_focus",
                    G_CALLBACK (on_entry_cino_grab_focus),
                    NULL);
  g_signal_connect ((gpointer) r_male, "toggled",
                    G_CALLBACK (on_r_male_toggled),
                    NULL);
  g_signal_connect ((gpointer) r_fmale, "toggled",
                    G_CALLBACK (on_r_fmale_toggled),
                    NULL);
  g_signal_connect ((gpointer) addo, "clicked",
                    G_CALLBACK (on_addo_clicked),
                    NULL);
  g_signal_connect ((gpointer) treeview1, "row_activated",
                    G_CALLBACK (on_treeview1_row_activated),
                    NULL);
  g_signal_connect ((gpointer) modifyo, "clicked",
                    G_CALLBACK (on_modifyo_clicked),
                    NULL);
  g_signal_connect ((gpointer) checkbutton2, "toggled",
                    G_CALLBACK (on_checkbutton2_toggled),
                    NULL);
  g_signal_connect ((gpointer) searcho, "clicked",
                    G_CALLBACK (on_searcho_clicked),
                    NULL);
  g_signal_connect ((gpointer) refresho1, "clicked",
                    G_CALLBACK (on_refresho1_clicked),
                    NULL);
  g_signal_connect ((gpointer) checkbutton1, "toggled",
                    G_CALLBACK (on_checkbutton1_toggled),
                    NULL);
  g_signal_connect ((gpointer) treeview2, "row_activated",
                    G_CALLBACK (on_treeview2_row_activated),
                    NULL);
  g_signal_connect ((gpointer) deleteo, "clicked",
                    G_CALLBACK (on_deleteo_clicked),
                    NULL);
  g_signal_connect ((gpointer) checkbutton3o, "toggled",
                    G_CALLBACK (on_checkbutton3o_toggled),
                    NULL);
  g_signal_connect ((gpointer) searcho4, "clicked",
                    G_CALLBACK (on_searcho4_clicked),
                    NULL);
  g_signal_connect ((gpointer) checkbutton4o, "toggled",
                    G_CALLBACK (on_checkbutton4o_toggled),
                    NULL);
  g_signal_connect ((gpointer) refresho4, "clicked",
                    G_CALLBACK (on_refresho4_clicked),
                    NULL);
  g_signal_connect ((gpointer) treeview3, "row_activated",
                    G_CALLBACK (on_treeview3_row_activated),
                    NULL);
  g_signal_connect ((gpointer) refresho3, "clicked",
                    G_CALLBACK (on_refresho3_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window1, window1, "window1");
  GLADE_HOOKUP_OBJECT (window1, fixed1, "fixed1");
  GLADE_HOOKUP_OBJECT (window1, notebook1, "notebook1");
  GLADE_HOOKUP_OBJECT (window1, fixed2, "fixed2");
  GLADE_HOOKUP_OBJECT (window1, label2, "label2");
  GLADE_HOOKUP_OBJECT (window1, label3, "label3");
  GLADE_HOOKUP_OBJECT (window1, label4, "label4");
  GLADE_HOOKUP_OBJECT (window1, label5, "label5");
  GLADE_HOOKUP_OBJECT (window1, label6, "label6");
  GLADE_HOOKUP_OBJECT (window1, label7, "label7");
  GLADE_HOOKUP_OBJECT (window1, label9, "label9");
  GLADE_HOOKUP_OBJECT (window1, entry_fnameo, "entry_fnameo");
  GLADE_HOOKUP_OBJECT (window1, entry_nameo, "entry_nameo");
  GLADE_HOOKUP_OBJECT (window1, entry_phoneo, "entry_phoneo");
  GLADE_HOOKUP_OBJECT (window1, label10, "label10");
  GLADE_HOOKUP_OBJECT (window1, label11, "label11");
  GLADE_HOOKUP_OBJECT (window1, label12, "label12");
  GLADE_HOOKUP_OBJECT (window1, spinbutton_dayo, "spinbutton_dayo");
  GLADE_HOOKUP_OBJECT (window1, spinbutton_montho, "spinbutton_montho");
  GLADE_HOOKUP_OBJECT (window1, spinbutton_yearo, "spinbutton_yearo");
  GLADE_HOOKUP_OBJECT (window1, label1, "label1");
  GLADE_HOOKUP_OBJECT (window1, label8, "label8");
  GLADE_HOOKUP_OBJECT (window1, entry_cino, "entry_cino");
  GLADE_HOOKUP_OBJECT (window1, labelerroro1, "labelerroro1");
  GLADE_HOOKUP_OBJECT (window1, label32, "label32");
  GLADE_HOOKUP_OBJECT (window1, combobox_blocko, "combobox_blocko");
  GLADE_HOOKUP_OBJECT (window1, combobox_levelo, "combobox_levelo");
  GLADE_HOOKUP_OBJECT (window1, r_male, "r_male");
  GLADE_HOOKUP_OBJECT (window1, r_fmale, "r_fmale");
  GLADE_HOOKUP_OBJECT (window1, addo, "addo");
  GLADE_HOOKUP_OBJECT (window1, label13, "label13");
  GLADE_HOOKUP_OBJECT (window1, fixed3, "fixed3");
  GLADE_HOOKUP_OBJECT (window1, entrycinre, "entrycinre");
  GLADE_HOOKUP_OBJECT (window1, entryblockre, "entryblockre");
  GLADE_HOOKUP_OBJECT (window1, treeview1, "treeview1");
  GLADE_HOOKUP_OBJECT (window1, label16, "label16");
  GLADE_HOOKUP_OBJECT (window1, labelerroro2, "labelerroro2");
  GLADE_HOOKUP_OBJECT (window1, modifyo, "modifyo");
  GLADE_HOOKUP_OBJECT (window1, checkbutton2, "checkbutton2");
  GLADE_HOOKUP_OBJECT (window1, searcho, "searcho");
  GLADE_HOOKUP_OBJECT (window1, refresho1, "refresho1");
  GLADE_HOOKUP_OBJECT (window1, checkbutton1, "checkbutton1");
  GLADE_HOOKUP_OBJECT (window1, label14, "label14");
  GLADE_HOOKUP_OBJECT (window1, fixed4, "fixed4");
  GLADE_HOOKUP_OBJECT (window1, treeview2, "treeview2");
  GLADE_HOOKUP_OBJECT (window1, labelerroro3, "labelerroro3");
  GLADE_HOOKUP_OBJECT (window1, label33, "label33");
  GLADE_HOOKUP_OBJECT (window1, entrycinree, "entrycinree");
  GLADE_HOOKUP_OBJECT (window1, entryblockree, "entryblockree");
  GLADE_HOOKUP_OBJECT (window1, deleteo, "deleteo");
  GLADE_HOOKUP_OBJECT (window1, checkbutton3o, "checkbutton3o");
  GLADE_HOOKUP_OBJECT (window1, searcho4, "searcho4");
  GLADE_HOOKUP_OBJECT (window1, checkbutton4o, "checkbutton4o");
  GLADE_HOOKUP_OBJECT (window1, refresho4, "refresho4");
  GLADE_HOOKUP_OBJECT (window1, searcho2, "searcho2");
  GLADE_HOOKUP_OBJECT (window1, fixed5, "fixed5");
  GLADE_HOOKUP_OBJECT (window1, treeview3, "treeview3");
  GLADE_HOOKUP_OBJECT (window1, label19, "label19");
  GLADE_HOOKUP_OBJECT (window1, refresho3, "refresho3");
  GLADE_HOOKUP_OBJECT (window1, label18, "label18");

  return window1;
}

GtkWidget*
create_windowmodi (void)
{
  GtkWidget *windowmodi;
  GtkWidget *fixed6;
  GtkWidget *entrytelephonemo;
  GtkWidget *entryprenommo;
  GtkObject *spinbuttonjourmo_adj;
  GtkWidget *spinbuttonjourmo;
  GtkObject *spinbuttonmoismo_adj;
  GtkWidget *spinbuttonmoismo;
  GtkObject *spinbuttonanneemo_adj;
  GtkWidget *spinbuttonanneemo;
  GtkWidget *label21;
  GtkWidget *label23;
  GtkWidget *label24;
  GtkWidget *label22;
  GtkWidget *label20;
  GtkWidget *label26;
  GtkWidget *label25;
  GtkWidget *label27;
  GtkWidget *label28;
  GtkWidget *label29;
  GtkWidget *entrynommo;
  GtkWidget *label31;
  GtkWidget *comboboxniveaumo;
  GtkWidget *comboboxblockmo;
  GtkWidget *rbhommemo;
  GSList *rbhommemo_group = NULL;
  GtkWidget *rbfemmemo;
  GtkWidget *save;
  GtkWidget *alignment1;
  GtkWidget *hbox1;
  GtkWidget *image1;
  GtkWidget *label30;

  windowmodi = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (windowmodi), _("modify student"));

  fixed6 = gtk_fixed_new ();
  gtk_widget_show (fixed6);
  gtk_container_add (GTK_CONTAINER (windowmodi), fixed6);

  entrytelephonemo = gtk_entry_new ();
  gtk_widget_show (entrytelephonemo);
  gtk_fixed_put (GTK_FIXED (fixed6), entrytelephonemo, 528, 168);
  gtk_widget_set_size_request (entrytelephonemo, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entrytelephonemo), 8226);

  entryprenommo = gtk_entry_new ();
  gtk_widget_show (entryprenommo);
  gtk_fixed_put (GTK_FIXED (fixed6), entryprenommo, 144, 168);
  gtk_widget_set_size_request (entryprenommo, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryprenommo), 8226);

  spinbuttonjourmo_adj = gtk_adjustment_new (1, 1, 31, 1, 10, 10);
  spinbuttonjourmo = gtk_spin_button_new (GTK_ADJUSTMENT (spinbuttonjourmo_adj), 1, 0);
  gtk_widget_show (spinbuttonjourmo);
  gtk_fixed_put (GTK_FIXED (fixed6), spinbuttonjourmo, 544, 256);
  gtk_widget_set_size_request (spinbuttonjourmo, 60, 27);

  spinbuttonmoismo_adj = gtk_adjustment_new (1, 1, 12, 1, 10, 10);
  spinbuttonmoismo = gtk_spin_button_new (GTK_ADJUSTMENT (spinbuttonmoismo_adj), 1, 0);
  gtk_widget_show (spinbuttonmoismo);
  gtk_fixed_put (GTK_FIXED (fixed6), spinbuttonmoismo, 624, 256);
  gtk_widget_set_size_request (spinbuttonmoismo, 60, 27);

  spinbuttonanneemo_adj = gtk_adjustment_new (1, 1980, 2050, 1, 10, 10);
  spinbuttonanneemo = gtk_spin_button_new (GTK_ADJUSTMENT (spinbuttonanneemo_adj), 1, 0);
  gtk_widget_show (spinbuttonanneemo);
  gtk_fixed_put (GTK_FIXED (fixed6), spinbuttonanneemo, 712, 256);
  gtk_widget_set_size_request (spinbuttonanneemo, 60, 27);

  label21 = gtk_label_new (_("First Name"));
  gtk_widget_show (label21);
  gtk_fixed_put (GTK_FIXED (fixed6), label21, 40, 88);
  gtk_widget_set_size_request (label21, 89, 25);

  label23 = gtk_label_new (_("Name"));
  gtk_widget_show (label23);
  gtk_fixed_put (GTK_FIXED (fixed6), label23, 56, 168);
  gtk_widget_set_size_request (label23, 80, 24);

  label24 = gtk_label_new (_("Level"));
  gtk_widget_show (label24);
  gtk_fixed_put (GTK_FIXED (fixed6), label24, 72, 248);
  gtk_widget_set_size_request (label24, 48, 24);

  label22 = gtk_label_new (_("Gender"));
  gtk_widget_show (label22);
  gtk_fixed_put (GTK_FIXED (fixed6), label22, 48, 216);
  gtk_widget_set_size_request (label22, 65, 24);

  label20 = gtk_label_new (_("Block"));
  gtk_widget_show (label20);
  gtk_fixed_put (GTK_FIXED (fixed6), label20, 456, 104);
  gtk_widget_set_size_request (label20, 49, 17);

  label26 = gtk_label_new (_("Phone"));
  gtk_widget_show (label26);
  gtk_fixed_put (GTK_FIXED (fixed6), label26, 432, 176);
  gtk_widget_set_size_request (label26, 80, 24);

  label25 = gtk_label_new (_("Date of Birth"));
  gtk_widget_show (label25);
  gtk_fixed_put (GTK_FIXED (fixed6), label25, 392, 240);
  gtk_widget_set_size_request (label25, 136, 32);

  label27 = gtk_label_new (_("Day"));
  gtk_widget_show (label27);
  gtk_fixed_put (GTK_FIXED (fixed6), label27, 544, 232);
  gtk_widget_set_size_request (label27, 49, 24);

  label28 = gtk_label_new (_("Month"));
  gtk_widget_show (label28);
  gtk_fixed_put (GTK_FIXED (fixed6), label28, 624, 232);
  gtk_widget_set_size_request (label28, 48, 24);

  label29 = gtk_label_new (_("Year"));
  gtk_widget_show (label29);
  gtk_fixed_put (GTK_FIXED (fixed6), label29, 704, 232);
  gtk_widget_set_size_request (label29, 64, 24);

  entrynommo = gtk_entry_new ();
  gtk_widget_show (entrynommo);
  gtk_fixed_put (GTK_FIXED (fixed6), entrynommo, 136, 88);
  gtk_widget_set_size_request (entrynommo, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entrynommo), 8226);

  label31 = gtk_label_new (_("Modify"));
  gtk_widget_show (label31);
  gtk_fixed_put (GTK_FIXED (fixed6), label31, 336, 16);
  gtk_widget_set_size_request (label31, 113, 32);

  comboboxniveaumo = gtk_combo_box_new_text ();
  gtk_widget_show (comboboxniveaumo);
  gtk_fixed_put (GTK_FIXED (fixed6), comboboxniveaumo, 144, 248);
  gtk_widget_set_size_request (comboboxniveaumo, 155, 33);
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxniveaumo), _("1"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxniveaumo), _("2"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxniveaumo), _("3"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxniveaumo), _("4"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxniveaumo), _("5"));

  comboboxblockmo = gtk_combo_box_new_text ();
  gtk_widget_show (comboboxblockmo);
  gtk_fixed_put (GTK_FIXED (fixed6), comboboxblockmo, 528, 96);
  gtk_widget_set_size_request (comboboxblockmo, 155, 33);
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxblockmo), _("1"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxblockmo), _("2"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxblockmo), _("3"));

  rbhommemo = gtk_radio_button_new_with_mnemonic (NULL, _("Male"));
  gtk_widget_show (rbhommemo);
  gtk_fixed_put (GTK_FIXED (fixed6), rbhommemo, 144, 216);
  gtk_widget_set_size_request (rbhommemo, 72, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (rbhommemo), rbhommemo_group);
  rbhommemo_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (rbhommemo));

  rbfemmemo = gtk_radio_button_new_with_mnemonic (NULL, _("Female"));
  gtk_widget_show (rbfemmemo);
  gtk_fixed_put (GTK_FIXED (fixed6), rbfemmemo, 224, 216);
  gtk_widget_set_size_request (rbfemmemo, 88, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (rbfemmemo), rbhommemo_group);
  rbhommemo_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (rbfemmemo));

  save = gtk_button_new ();
  gtk_widget_show (save);
  gtk_fixed_put (GTK_FIXED (fixed6), save, 256, 320);
  gtk_widget_set_size_request (save, 232, 40);

  alignment1 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment1);
  gtk_container_add (GTK_CONTAINER (save), alignment1);

  hbox1 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox1);
  gtk_container_add (GTK_CONTAINER (alignment1), hbox1);

  image1 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image1);
  gtk_box_pack_start (GTK_BOX (hbox1), image1, FALSE, FALSE, 0);

  label30 = gtk_label_new_with_mnemonic (_("Save modifications"));
  gtk_widget_show (label30);
  gtk_box_pack_start (GTK_BOX (hbox1), label30, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) entrynommo, "grab_focus",
                    G_CALLBACK (on_entrynommo_grab_focus),
                    NULL);
  g_signal_connect ((gpointer) rbhommemo, "toggled",
                    G_CALLBACK (on_rbhommemo_toggled),
                    NULL);
  g_signal_connect ((gpointer) rbfemmemo, "toggled",
                    G_CALLBACK (on_rbfemmemo_toggled),
                    NULL);
  g_signal_connect ((gpointer) save, "clicked",
                    G_CALLBACK (on_save_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (windowmodi, windowmodi, "windowmodi");
  GLADE_HOOKUP_OBJECT (windowmodi, fixed6, "fixed6");
  GLADE_HOOKUP_OBJECT (windowmodi, entrytelephonemo, "entrytelephonemo");
  GLADE_HOOKUP_OBJECT (windowmodi, entryprenommo, "entryprenommo");
  GLADE_HOOKUP_OBJECT (windowmodi, spinbuttonjourmo, "spinbuttonjourmo");
  GLADE_HOOKUP_OBJECT (windowmodi, spinbuttonmoismo, "spinbuttonmoismo");
  GLADE_HOOKUP_OBJECT (windowmodi, spinbuttonanneemo, "spinbuttonanneemo");
  GLADE_HOOKUP_OBJECT (windowmodi, label21, "label21");
  GLADE_HOOKUP_OBJECT (windowmodi, label23, "label23");
  GLADE_HOOKUP_OBJECT (windowmodi, label24, "label24");
  GLADE_HOOKUP_OBJECT (windowmodi, label22, "label22");
  GLADE_HOOKUP_OBJECT (windowmodi, label20, "label20");
  GLADE_HOOKUP_OBJECT (windowmodi, label26, "label26");
  GLADE_HOOKUP_OBJECT (windowmodi, label25, "label25");
  GLADE_HOOKUP_OBJECT (windowmodi, label27, "label27");
  GLADE_HOOKUP_OBJECT (windowmodi, label28, "label28");
  GLADE_HOOKUP_OBJECT (windowmodi, label29, "label29");
  GLADE_HOOKUP_OBJECT (windowmodi, entrynommo, "entrynommo");
  GLADE_HOOKUP_OBJECT (windowmodi, label31, "label31");
  GLADE_HOOKUP_OBJECT (windowmodi, comboboxniveaumo, "comboboxniveaumo");
  GLADE_HOOKUP_OBJECT (windowmodi, comboboxblockmo, "comboboxblockmo");
  GLADE_HOOKUP_OBJECT (windowmodi, rbhommemo, "rbhommemo");
  GLADE_HOOKUP_OBJECT (windowmodi, rbfemmemo, "rbfemmemo");
  GLADE_HOOKUP_OBJECT (windowmodi, save, "save");
  GLADE_HOOKUP_OBJECT (windowmodi, alignment1, "alignment1");
  GLADE_HOOKUP_OBJECT (windowmodi, hbox1, "hbox1");
  GLADE_HOOKUP_OBJECT (windowmodi, image1, "image1");
  GLADE_HOOKUP_OBJECT (windowmodi, label30, "label30");

  return windowmodi;
}

